name : lab-git-ci-HayalAhl/.github/workflows/main.yml

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
